### ISSUE TITLE
Referenced conference topics should be broader

### ISSUE THREAD

**Issue by YannisBres** [FroMage/RivieraDEV#14]
On the home page (as far as it fits on two lines) :

* FR :  Des sujets variés :  Java & langages alternatifs, Front-end & UX, Mobile & IoT, Big Data & AI, NoSql, Containers & Cloud, Performance, Agilité, DevOps...
* EN :  A rich mix of topics: Java & alternate languages, Front-end & UX, Mobile & IoT, Big Data & AI, NoSql, Containers & Cloud, Performance, Agility, DevOps.

On the program page, add :

* FR :
Riviera DEV est une conférence sur 2 jours avec au moins 3 tracks sur un large panel de sujets :  Java et la JVM (présent et futur), langages alternatifs, technologies Front-end technologies et UX, Mobile et IoT, Big Data et Machine Learning, NoSql, Containers, VMs et Cloud Computing, Performance, Programmation réactive, Agilité, bonnes pratiques, DevOps, ...
Le programme n'est pas e-ncore disponible, mais vous pouvez consulter le programme de l'édition 2015 [http://2015.rivieradev.fr/programme] et celui de 2016 [http://2016.rivieradev.fr/programme].
Abonnez-vous [...]
* EN :
Riviera DEV is a 2 days conference with at least 3 tracks on a rich mix of topics :  Java and the JVM (present and future), alternate languages, Front-end technologies and UX, Mobile and IoT, Big Data and Machine Learning, NoSql, Containers, VMs and Cloud Computing, Performance, Reactive Programming, Agility, Good Practices, DevOps, ...
The program is not available yet, but you can have a look at the 2015 session [http://2015.rivieradev.fr/programme] as well as the 2016 session [http://2016.rivieradev.fr/programme].
Subscribe [...]

The 3 first blocks on the home page ("A conference for developpers, but not only", etc.) should be links to the program page.

**Comment by FroMage** [comment]
PR, pas issue !!!

**Comment by LowDoll** [comment]
+1
@YannisBres, balance direct tes changements dans le dossier conf, si ça sied à l'un des owners, tes changements sont activés dans la foulée, ça fait gagner du temps à tout le monde.

Sinon, NoSql -> NoSQL (please)

**Comment by mlegait** [comment]
Comme il y avait un peu de design à faire, que j'ai vraiment envie que le site ouvre enfin et que je suis très gentille :-P j'ai pris le point, je vous laisse vérifier.
D'ailleurs je viens de voir que je commit en tant que Jean-Michael, mystère à élucider ...

**Comment by YannisBres** [comment]
Merci Jean-Michael !  ;-)
          Yannis


2016-12-07 22:16 GMT+01:00 Michèle <notifications@github.com>:
