### ISSUE TITLE
Fix map issue on front-page

### ISSUE THREAD

**Issue by FroMage** [FroMage/RivieraDEV#4]

**Comment by Jean-Michael** [comment]
J'ai fixé le problème de la Google Map qui ne s'affichait pas en ajoutant une API Key. Par contre, il ne faut pas la sauver dans le code (d'après les recommandations Google).
Du coup, j'ai créé un nouvel objet "Configuration", qui permet de créer des configurations (key/value) dans le back office. On aura ensuite qu'à rajouter l'API KEY dans le back office. N'hésite pas si tu as des remarques sur ce nouvel objet.

Concernant l'API KEY,  je l'ai restreint aux domaines *.rivieradev.fr/* et *.rivieradev.com/* du coup si tu testes en local tu auras l'erreur "RefererNotAllowedMapError" mais ça devrait fonctionner nickel sur le site 2017.rivieradev.fr ;)

**Comment by FroMage** [comment]
Normalement non on fait pas comme ça on file une clef pour localhost dans la config, et une pour la prod dans un autre fichier de config. Après, on peut foutre ça en base mais il nous faudrait une valeur qui marche en localhost aussi.

**Comment by Jean-Michael** [comment]
Je n'ai pas voulu la mettre dans un fichier de config car la doc de Google disait de ne pas la sauver sur un répo public ( https://support.google.com/googleapi/answer/6310037?hl=fr ).
Du coup, j'ai fais en sorte qu'on puisse ajouter/modifier une API Key depuis l'interface d'admin pour éviter de faire des requêtes à la main directement en BD.

Et je viens de vérifier le code, c'est bon ça marche en local :)
En fait, pour résumer :
En local, si la clé n'est pas définie alors la google map fonctionne quand même.
MAIS en Prod/Staging, il FAUT une API Key sinon la carte ne fonctionne pas c'est très certainement une restriction google. L'API KEY de Prod ne peut pas être utilisée en local, car je l'ai restreinte pour ne fonctionner qu'avec les domaines *.rivieradev.fr et *.rivieradev.com afin de suivre les recommandations de sécurité décrites par Google.
