### ISSUE TITLE
Add the workshops back

### ISSUE THREAD

**Issue by FroMage** [FroMage/RivieraDEV#9]
The whole "we're not just devs" theme is missing entirely, we need to add it back, including on the CFP page to explain what those workshops are about.

**Comment by sebastienblanc** [comment]
Yes, we need some pictures like : 

![](https://pbs.twimg.com/media/ClFKbSnWEAEzbbV.jpg)

![](https://pbs.twimg.com/media/CHOMPiEWkAASIt-.jpg)

"For sure we love to code and we like to listen to really technical presentations but  we strongly believe that during a conference, sometimes,  you also want to relax a bit by learning completely  different things like : making sushis, learn picklocking and spend a hour doing a Yoga session. At RivieraDev, we push to have these kinds of workshops ... " well to be reviewed for sure

**Comment by FroMage** [comment]
I just added some photos to the CFP, and some text to explain the talks, but they need to be made to look good by @Jean-Michael and the text has to be fixed by @sebastienblanc our CFP head.

Source of photos from https://plus.google.com/photos/104322794282801309280/album/6307923088378568513 and https://twitter.com/RivieraDEV/media
